services:
  - type: web
    name: chatsito
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://postgres:Lunita48@db.yeheyhewslionqxzftji.supabase.co:5432/postgres?sslmode=require
